# Generated by Django 6.0 on 2025-12-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
